<a href="https://colab.research.google.com/github/ZeynepAkkus/DAwPy/blob/main/DAwPy_Lab1Zeyn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
b = np.array([[1,2,3],[6,7,8]])

In [7]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [8]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.zeros((3,3)) # tuple değer şeklinde yazılmalı 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.full ((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.arange(5,60,3) # arange array +range demektir

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [14]:
np.linspace(2,10,5) # 2 den başla 10 a kadar ilerle 5 parçaya böl demek 

array([ 2.,  4.,  6.,  8., 10.])

In [15]:
np.random.rand(3,3)  # ortalaması 1 olacak şekilde random sayılar verir 0-1 arası sayılar verir !!!

array([[0.67107824, 0.24358663, 0.28431662],
       [0.51237347, 0.20059437, 0.40476997],
       [0.88923994, 0.03641293, 0.03612925]])

In [16]:
np.random.randn(3,3)   # varyansı 1 olacak şekilde sayılar verir kontrol et !!!!

array([[ 2.55635667e-01, -2.78091381e-04,  2.92913515e-01],
       [ 6.25781620e-01, -1.33560371e+00, -7.08100662e-01],
       [-5.60975791e-01, -4.89426776e-01, -7.19444265e-01]])

In [17]:
z = np.random.randint(2,12,size =(5,3))

In [18]:
z

array([[ 9, 10,  4],
       [ 9, 10, 10],
       [ 9,  7,  3],
       [ 9, 11,  5],
       [ 7,  3,  5]])

In [19]:
z.shape # ileriki seviyelerde shape bakarak deep learnine uygun olup olmadığı kontrol edilir eğer uygun değilse reshape yapılarak modele uygun hale getirirlir.

(5, 3)

In [20]:
z = z.reshape(3,5) # reshape yaparken katmanları olmalı yani ilk yapılan 3*5 15 ise yapılacak olan rehape de onun katmanları olmak zorundadır

In [21]:
z

array([[ 9, 10,  4,  9, 10],
       [10,  9,  7,  3,  9],
       [11,  5,  7,  3,  5]])

In [22]:
z = z.reshape(-1,5) # hesaplamak istemiyorsak - yazarak kendi hesaplamasını isteyebilriz

In [23]:
z

array([[ 9, 10,  4,  9, 10],
       [10,  9,  7,  3,  9],
       [11,  5,  7,  3,  5]])

In [24]:
z = z.ravel() #reshape yerine kullanabilecek alternatif bir fonksiyondur

In [25]:
z

array([ 9, 10,  4,  9, 10, 10,  9,  7,  3,  9, 11,  5,  7,  3,  5])

In [26]:
z.max()

11

In [27]:
z.min()

3

In [28]:
z.argmax() # max olan sayının yerini verir

10

In [29]:
z.argmin() # min olan sayının yerini verir

8

In [ ]:
## CONCATANATE tabloları birleştirmek demektir

In [30]:
my_arr = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)

In [31]:
my_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
my_arrar_1 = np.array ([3,4,5,6,7,8,9,10,11,12]).reshape(5,2)

In [33]:
my_arrar_1

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [34]:
my_con= np.concatenate([my_arr,my_arrar_1],axis=1)

In [35]:
my_con

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [36]:
my_con[1,[2,3]] # 1.satır 2.sütun

array([5, 6])

In [37]:
my_con[[3,1],2]

array([9, 5])

In [38]:
my_con[0:2,1:3] # kısmi slincing 0 dan 2 ye kadar - 1 den 3 e kadar 

array([[1, 3],
       [3, 5]])

In [39]:
my_con[:,[0,3]]

array([[ 0,  4],
       [ 2,  6],
       [ 4,  8],
       [ 6, 10],
       [ 8, 12]])

In [ ]:
##stacking

In [41]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [42]:
a

array([[1, 2],
       [3, 4]])

In [43]:
b

array([[5, 6],
       [7, 8]])

In [44]:
x = np.stack((a,b))
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [45]:
x.ndim

3

In [46]:
x.shape

(2, 2, 2)

In [47]:
y=np.hstack((a,b)) # h yatay demek olduğu için işlem yönünü gösterir yatayda eklemleme yapar 3 boyutlu şekilde

In [48]:
y

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [49]:
y=np.vstack((a,b))
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
array_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])

In [53]:
biggerthan5 = array_1>5
biggerthan5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [54]:
array_1[biggerthan5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [55]:
array_1[array_1<5]

array([1, 2, 3, 4])

In [56]:
array_1[(array_1<10)& (array_1>3)] # bu şeilde çiftli çoklu filktrelemede yapabilriiz

array([4, 5, 6, 7, 8, 9])

In [ ]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

In [57]:
np.exp(x)


array([[[2.71828183e+00, 7.38905610e+00],
        [2.00855369e+01, 5.45981500e+01]],

       [[1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03]]])

In [58]:
import pandas as pd

In [59]:
my_list = [1,2,3,4,5,6,7,8]
a=np.array(my_list)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
pd.Series(my_list) # labellanmış array deniliyor direk inexliyor pandas ve int olmak zorunda değil 

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [61]:
labels = ['X','y','z', 'h']
my_list = [5, 10, 15, 20]
arr = np.array([25, 50, 75, 100])
d = {'a': 10, 'b': 20, 'c': 30, 'd':40}

In [62]:
pd.Series(my_list,index=labels) #bu sayede artık serimize x y z h üzerinden ulaşabiliriz

X     5
y    10
z    15
h    20
dtype: int64

In [63]:
pd.Series(arr)

0     25
1     50
2     75
3    100
dtype: int64

In [ ]:
# keylerle de ulaşılabiliyor 

In [64]:
pd.Series(d)

a    10
b    20
c    30
d    40
dtype: int64

In [65]:
mix_data = [7,"dog",False,np.arange]

In [66]:
ser = pd.Series([5,10,15,20,25,30], index = ['USA', 'Germany','France', 'UK','Turkey','Greece'])

In [67]:
ser

USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64

In [69]:
ser.sort_values()

USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64

In [70]:
ser.sort_index()

France     15
Germany    10
Greece     30
Turkey     25
UK         20
USA         5
dtype: int64

In [71]:
"Holand"in ser

False

In [85]:
ser.isin([25])

USA        False
Germany    False
France     False
UK         False
Turkey      True
Greece     False
dtype: bool

In [73]:
ser.keys()

Index(['USA', 'Germany', 'France', 'UK', 'Turkey', 'Greece'], dtype='object')

In [74]:
ser.items

<bound method Series.items of USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64>

In [76]:
for key,value in ser.items():
  print(key,value)

USA 5
Germany 10
France 15
UK 20
Turkey 25
Greece 30


In [77]:
m = np.arange(1,30,2).reshape((3,5))

In [78]:
m

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [81]:
df= pd.DataFrame(m,columns= ["col1","col2","col3","col4","col5"])
df

col1  col2  col3  col4  col5
0     1     3     5     7     9
1    11    13    15    17    19
2    21    23    25    27    29

In [82]:
df.head(1)

col1  col2  col3  col4  col5
0     1     3     5     7     9

In [83]:
df.tail(2)

col1  col2  col3  col4  col5
1    11    13    15    17    19
2    21    23    25    27    29

In [84]:
df.sample(2)

col1  col2  col3  col4  col5
1    11    13    15    17    19
0     1     3     5     7     9