<a href="https://colab.research.google.com/github/ZeynepAkkus/DAwPy/blob/main/DAwPy3_Session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
import matplotlib.pyplot as plt

In [5]:
np.array ([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
serr = pd.Series([11,12,13,14,15])

In [8]:
type(serr)

pandas.core.series.Series

In [9]:
serr

0    11
1    12
2    13
3    14
4    15
dtype: int64

In [10]:
serr.size

5

In [11]:
len(serr)

5

In [12]:
serr.nim

AttributeError: ignored

In [13]:
serr.ndim # 1 çıkıyor çünkü 1 tane serie olarak görüyor o yüzden dimensionu 1 veriyor.

1

In [14]:
serr.values  # numpy return etti iterable bir yapı yani döngüsel bir yapı for ile içinde dolaşabilirim

array([11, 12, 13, 14, 15])

In [16]:
[i for i in serr.values]

[11, 12, 13, 14, 15]

In [17]:
serr2 = pd.Series([11,21,13,41,15,61,11,21,13,41,15,61,11,21,13,41,15,61])

In [18]:
serr2

0     11
1     21
2     13
3     41
4     15
5     61
6     11
7     21
8     13
9     41
10    15
11    61
12    11
13    21
14    13
15    41
16    15
17    61
dtype: int64

In [19]:
serr2.head(10)

0    11
1    21
2    13
3    41
4    15
5    61
6    11
7    21
8    13
9    41
dtype: int64

In [21]:
serr2.tail(3)

15    41
16    15
17    61
dtype: int64

In [22]:
list("clarusway")

['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y']

In [24]:
pd.Series(list("clarusway"))

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [25]:
data = ["paris", "london" , "ankara"]
index = ["x" ,"y","z"]

In [26]:
pd.Series(data,index)

x     paris
y    london
z    ankara
dtype: object

In [29]:
Score = [70,60,90,85,99.5]
index = ["D","A","C","B","E"]
pd.Series(Score,index)

D    70.0
A    60.0
C    90.0
B    85.0
E    99.5
dtype: float64

In [30]:
dit = {"D":10,"E":20 , "A":-30,"B":99 , "c":1.1}
pd.Series(dit)

D    10.0
E    20.0
A   -30.0
B    99.0
c     1.1
dtype: float64

In [ ]:
set 

In [31]:
ser1 = pd.Series([1,2,3,4], index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4], index = ['USA', 'Germany','Italy', 'Japan'])

In [32]:
ser1.index

Index(['USA', 'Germany', 'USSR', 'Japan'], dtype='object')

In [33]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [34]:
ser1.values

array([1, 2, 3, 4])

In [36]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [37]:
ser1.sort_values()

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [38]:
ser1["Germany"]

2

In [39]:
ser1["Japan"]

4

In [40]:
ser1["Japan","Germany"] # birden fazla index vermek istiyorsak bir liste içinde vermemiz gerekiyor

KeyError: ignored

In [41]:
ser1[["Japan","Germany"]]

Japan      4
Germany    2
dtype: int64

In [42]:
ser1.Japan

4

In [43]:
ser1+ser2 # iki listede farklı olan şeyleri toplayamadığı için nan çıkıyor ama diğer ülkelerde aynı olanların değerlerini topladığını görüyoruz sql deki innerjoin mantığı gibi

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [48]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason","adam"])
panser

ValueError: ignored

In [49]:
panser["orion":"adam"]

KeyError: ignored