<a href="https://colab.research.google.com/github/ZeynepAkkus/DAwPy/blob/main/DAwPy_Session4Zeynep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%config IPCompleter.greedy=True
!pip install ipython --upgrade
!pip install jedi
!pip3 install jupyter-tabnine
!jupyter nbextension install --py jupyter_tabnine
!jupyter nbextension enable --py jupyter_tabnine
!jupyter serverextension enable --py jupyter_tabnine

Installing C:\Users\W-10\anaconda3\lib\site-packages\jupyter_tabnine\static -> jupyter_tabnine
Up to date: C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\main.css
Up to date: C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\main.js
Up to date: C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\README.md
Up to date: C:\ProgramData\jupyter\nbextensions\jupyter_tabnine\tabnine.yaml
- Validating: ok

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable jupyter_tabnine --py
    
Enabling notebook extension jupyter_tabnine/main...
      - Validating: ok
Enabling: jupyter_tabnine
- Writing config: C:\Users\W-10\.jupyter
    - Validating...
      jupyter_tabnine  ok


In [ ]:
df = pd.read_csv("data/missingData.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'data/missingData.csv'

import pandas as pd

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import seaborn as sns

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
data = [1,3,5,7,9]

In [ ]:
data

[1, 3, 5, 7, 9]

In [ ]:
pd.DataFrame(data,columns=["col1"])

col1
0     1
1     3
2     5
3     7
4     9

In [ ]:
pd.Series(data)

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [ ]:
# ikisinin farkı pandas series de şuan için sadece 1 tane coloumn var 
#pandasseries de col ismi yok dataframede col ismi vardır data fram seriesin gelişmiş hali diyebiliriz

In [ ]:
data2= np.arange(1,24,2).reshape(3,4)
data2

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
pd.DataFrame(data2,columns =["col1","col2","col3","col4"])

col1  col2  col3  col4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [ ]:
df = pd.DataFrame(data2,columns =["col1","col2","col3","col4"],index=["a","b","c"])

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.size


NameError: name 'df' is not defined

In [ ]:
df.ndim

2

In [ ]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
df.columns

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [ ]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
len(df)

3

In [ ]:
df.keys()

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [ ]:
df

col1  col2  col3  col4
a     1     3     5     7
b     9    11    13    15
c    17    19    21    23

In [ ]:
df.col1

a     1
b     9
c    17
Name: col1, dtype: int32

In [ ]:
df["col1"]

a     1
b     9
c    17
Name: col1, dtype: int32

In [ ]:
df.mean()

col1     9.0
col2    11.0
col3    13.0
col4    15.0
dtype: float64

In [ ]:
s1 = np.random.randint(2,10, size = 40)
s2 = np.random.randint(30,100, size = 40)
s3 = np.random.randint(100,150, size = 40)

In [ ]:
s1

array([8, 5, 6, 5, 3, 8, 5, 2, 2, 6, 5, 6, 8, 7, 3, 9, 5, 7, 3, 8, 4, 4,
       2, 6, 9, 7, 3, 5, 8, 8, 8, 5, 7, 7, 8, 2, 3, 3, 5, 4])

In [ ]:
myDict = {"var":s1, "var2":s2,"var3":s3}

In [ ]:
myDict

{'var': array([8, 5, 6, 5, 3, 8, 5, 2, 2, 6, 5, 6, 8, 7, 3, 9, 5, 7, 3, 8, 4, 4,
        2, 6, 9, 7, 3, 5, 8, 8, 8, 5, 7, 7, 8, 2, 3, 3, 5, 4]),
 'var2': array([76, 45, 81, 46, 34, 62, 49, 96, 63, 85, 49, 32, 79, 51, 60, 55, 36,
        58, 76, 39, 84, 45, 58, 56, 99, 42, 40, 58, 87, 31, 54, 30, 83, 53,
        84, 84, 67, 60, 53, 88]),
 'var3': array([110, 105, 119, 126, 118, 112, 102, 123, 114, 100, 129, 131, 109,
        111, 137, 140, 112, 103, 127, 114, 135, 113, 116, 135, 137, 139,
        109, 116, 124, 110, 129, 120, 113, 100, 137, 112, 124, 101, 119,
        126])}

In [ ]:
dfDict = pd.DataFrame(myDict)

In [ ]:
dfDict

var  var2  var3
0     8    76   110
1     5    45   105
2     6    81   119
3     5    46   126
4     3    34   118
5     8    62   112
6     5    49   102
7     2    96   123
8     2    63   114
9     6    85   100
10    5    49   129
11    6    32   131
12    8    79   109
13    7    51   111
14    3    60   137
15    9    55   140
16    5    36   112
17    7    58   103
18    3    76   127
19    8    39   114
20    4    84   135
21    4    45   113
22    2    58   116
23    6    56   135
24    9    99   137
25    7    42   139
26    3    40   109
27    5    58   116
28    8    87   124
29    8    31   110
30    8    54   129
31    5    30   120
32    7    83   113
33    7    53   100
34    8    84   137
35    2    84   112
36    3    67   124
37    3    60   101
38    5    53   119
39    4    88   126

In [ ]:
dfDict[3:5]

var  var2  var3
3    5    46   126
4    3    34   118

In [ ]:
dfDict2 = dfDict[3:5]
dfDict2

var  var2  var3
3    5    46   126
4    3    34   118

In [ ]:
dfDict2.index = ["a","b"]
dfDict2

var  var2  var3
a    5    46   126
b    3    34   118

In [ ]:
dfDict2.columns = ["X","Y","Z"]
dfDict2

X   Y    Z
a  5  46  126
b  3  34  118

In [ ]:
pd.DataFrame(dfDict2.values,index=["c","d"])

In [ ]:
np.random.randn(5,4)

array([[-0.62369585,  0.56157134,  0.70861269,  0.25595418],
       [-0.22701176, -1.41945069, -1.91007035,  0.4993322 ],
       [ 0.51431496, -0.39611194, -1.64615926,  0.09996907],
       [ 0.7699185 , -2.77969291, -0.02637496,  2.15827688],
       [-0.29438506,  1.88366506,  0.81352781,  0.6024995 ]])

In [ ]:
np.random.seed(101)

In [ ]:
np.random.randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [ ]:
np.random.seed(101)
df3 = pd.DataFrame(  np.random.randn(5,4),
                   index = ['A', 'B', 'C', 'D', 'E'],
                   columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
df3.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
df3[["W"]]

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [ ]:
df3[["W","Y"]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [ ]:
df3.loc[:,"W":"Z"]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.loc["B":"D","W":"Z"]

W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [ ]:
df3["X"]

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [ ]:
df3["Y"]

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [ ]:
df3["X"]+df3["Y"]

A    1.536102
B   -1.167395
C    1.268936
D   -1.692109
E    4.584725
dtype: float64

In [ ]:
df3["X"]*df3["Y"]

A    0.570325
B    0.270806
C    0.391387
D    0.708208
E    5.156577
dtype: float64

In [ ]:
df3["X"]/df3["Y"]**2

A    0.761919
B   -0.443969
C    2.646661
D   -0.871334
E    0.291377
dtype: float64

In [ ]:
#dataframe e yeni sütun ekleme (append ile satır eklenir altına ,)

In [ ]:
df3["Yeni"]=df3["W"]*df3["X"]+df3["Y"]**2-df3["Z"]
df3

W         X         Y         Z      Yeni
A  2.706850  0.628133  0.907969  0.503826  2.020844
B  0.651118 -0.319318 -0.848077  0.605965 -0.094644
C -2.018168  0.740122  0.528813 -0.589001 -0.625047
D  0.188695 -0.758872 -0.933237  0.955057 -0.227320
E  0.190794  1.978757  2.605967  0.683509  6.485092

In [ ]:
df3["Yeni2"]=df3["W"]*df3["X"]+df3["Y"]**2-df3["Z"].mean()
df3

W         X         Y         Z      Yeni     Yeni2
A  2.706850  0.628133  0.907969  0.503826  2.020844  2.092798
B  0.651118 -0.319318 -0.848077  0.605965 -0.094644  0.079450
C -2.018168  0.740122  0.528813 -0.589001 -0.625047 -1.645918
D  0.188695 -0.758872 -0.933237  0.955057 -0.227320  0.295865
E  0.190794  1.978757  2.605967  0.683509  6.485092  6.736730

In [ ]:
df3.drop("Yeni",axis = 1)

W         X         Y         Z     Yeni2
A  2.706850  0.628133  0.907969  0.503826  2.092798
B  0.651118 -0.319318 -0.848077  0.605965  0.079450
C -2.018168  0.740122  0.528813 -0.589001 -1.645918
D  0.188695 -0.758872 -0.933237  0.955057  0.295865
E  0.190794  1.978757  2.605967  0.683509  6.736730

In [ ]:
df3

W         X         Y         Z      Yeni     Yeni2
A  2.706850  0.628133  0.907969  0.503826  2.020844  2.092798
B  0.651118 -0.319318 -0.848077  0.605965 -0.094644  0.079450
C -2.018168  0.740122  0.528813 -0.589001 -0.625047 -1.645918
D  0.188695 -0.758872 -0.933237  0.955057 -0.227320  0.295865
E  0.190794  1.978757  2.605967  0.683509  6.485092  6.736730

In [ ]:
df3 = df3.drop("Yeni",axis = 1)

In [ ]:
df3

W         X         Y         Z     Yeni2
A  2.706850  0.628133  0.907969  0.503826  2.092798
B  0.651118 -0.319318 -0.848077  0.605965  0.079450
C -2.018168  0.740122  0.528813 -0.589001 -1.645918
D  0.188695 -0.758872 -0.933237  0.955057  0.295865
E  0.190794  1.978757  2.605967  0.683509  6.736730

In [ ]:
df3.drop(["Y","Yeni2"],axis = 1)

W         X         Z
A  2.706850  0.628133  0.503826
B  0.651118 -0.319318  0.605965
C -2.018168  0.740122 -0.589001
D  0.188695 -0.758872  0.955057
E  0.190794  1.978757  0.683509

In [ ]:
df3.drop(["Y","Yeni2"],axis = 1,inplace= True)

### 

In [ ]:
df3

W         X         Z
A  2.706850  0.628133  0.503826
B  0.651118 -0.319318  0.605965
C -2.018168  0.740122 -0.589001
D  0.188695 -0.758872  0.955057
E  0.190794  1.978757  0.683509

In [ ]:
df3.drop(["C","E"],axis=0,inplace=True)

In [ ]:
df3

W         X         Z
A  2.706850  0.628133  0.503826
B  0.651118 -0.319318  0.605965
D  0.188695 -0.758872  0.955057

In [ ]:
m=np.random.randint(1,40, size=(8,4))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3",'var4'])
df4

var1  var2  var3  var4
0     8    11    39    10
1    19     8    16     1
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23
7    10     3    19    29

In [ ]:
df4.loc[2]  # seri olarak verdi

var1    13
var2    18
var3    12
var4    16
Name: 2, dtype: int32

In [ ]:
df4.loc[2:6] #dataframe olarak verdi 

var1  var2  var3  var4
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23

In [ ]:
df4.index='a b c d e f g h'.split()
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

### loc aldığı ilk parametre satırdır

In [ ]:
df4.loc["c"]

var1    13
var2    18
var3    12
var4    16
Name: c, dtype: int32

In [ ]:
df4.loc["c":"f"]

var1  var2  var3  var4
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23

In [ ]:
df4.loc["c":"f","var1":"var3"]

var1  var2  var3
c    13    18    12
d    34    30    25
e    20    36    31
f    21    28     9

In [ ]:
df4.loc[["c","f"],["var1","var3"]]

var1  var3
c    13    12
f    21     9

In [ ]:
df4.loc[["c","f"],["var1","var3","var2"]]

var1  var3  var2
c    13    12    18
f    21     9    28

In [ ]:
df4.iloc[1:4,2:4]

var3  var4
b    16     1
c    12    16
d    25    37

In [ ]:
# 4 ler dahil değildir 

In [ ]:
df4.iloc[1:4,2:3]

var3
b    16
c    12
d    25

In [ ]:
df3

W         X         Z
A  2.706850  0.628133  0.503826
B  0.651118 -0.319318  0.605965
D  0.188695 -0.758872  0.955057

In [ ]:
df3.iloc[:,2:4]

Z
A  0.503826
B  0.605965
D  0.955057

In [ ]:
df3["X"]>0

A     True
B    False
D    False
Name: X, dtype: bool

In [ ]:
df3[df3["X"]>0]

W         X         Z
A  2.70685  0.628133  0.503826

In [ ]:
df3[(df3["X"] > 0) & (df3["Z"] > 0)]

W         X         Z
A  2.70685  0.628133  0.503826

In [ ]:
df3[df3.Z>0][["W"]] # örneğin yaşı 20den büyük olanların maaşını getir ya da maaşı x den daha fazla olanların yaşını getir 

W
A  2.706850
B  0.651118
D  0.188695